version: "3"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on: 
      - db
    volumes:
      - ./:/app 
  db:
    image: postgres:15.2  
    environment:
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: testdb 
    ports: 
      - "5432:5432"
